"
A PssBorderRadiusModelTest is a test class for testing the behavior of PssBorderRadiusModel
"
Class {
	#name : #PssBorderRadiusModelTest,
	#superclass : #TestCase,
	#category : #'PharoStylesheet-Model-Tests-Declarations'
}

{ #category : #tests }
PssBorderRadiusModelTest >> testBorderRadius1 [
	self flag: #toDo.
	self assert: false.
]

{ #category : #tests }
PssBorderRadiusModelTest >> testBorderRadius2 [
	self flag: #toDo.
	self assert: false.
]

{ #category : #tests }
PssBorderRadiusModelTest >> testBorderRadius3 [
	self flag: #toDo.
	self assert: false.
]

{ #category : #tests }
PssBorderRadiusModelTest >> testBorderRadius4 [
	self flag: #toDo.
	self assert: false.
]
